/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.tsx",
    "./src/components/**/*.tsx",
    "../shared/**/*.{js,jsx,ts,tsx}"
  ],
  safelist: [
    'bg-bluebonnet-600',
    'bg-bluebonnet-700',
    'bg-bluebonnet-800',
    'text-bluebonnet-600',
    'text-bluebonnet-700',
    'text-texas-green-600',
    'bg-texas-green-600',
    'flex',
    'grid',
    'p-4',
    'p-6',
    'p-8',
    'm-4',
    'm-6',
    'w-full',
    'h-full',
    'max-w-7xl',
    'container',
    'mx-auto',
    'space-y-4',
    'space-y-6',
    'space-y-8',
    'gap-4',
    'gap-6',
    'gap-8',
    'rounded-lg',
    'shadow-lg',
    'border',
    'border-gray-200',
    'text-center',
    'text-left',
    'text-right',
    'font-bold',
    'font-medium',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'mb-4',
    'mb-6',
    'mt-4',
    'mt-6',
    'px-4',
    'px-6',
    'py-2',
    'py-4',
    'hover:bg-bluebonnet-700',
    'hover:bg-bluebonnet-800',
    'hover:text-bluebonnet-600'
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        bluebonnet: {
          50: "var(--bluebonnet-50)",
          100: "var(--bluebonnet-100)",
          200: "var(--bluebonnet-200)",
          300: "var(--bluebonnet-300)",
          400: "var(--bluebonnet-400)",
          500: "var(--bluebonnet-500)",
          600: "var(--bluebonnet-600)",
          700: "var(--bluebonnet-700)",
          800: "var(--bluebonnet-800)",
          900: "var(--bluebonnet-900)",
        },
        "texas-green": {
          100: "var(--texas-green-100)",
          400: "var(--texas-green-400)",
          500: "var(--texas-green-500)",
          600: "var(--texas-green-600)",
        },
        earth: {
          100: "var(--earth-100)",
          400: "var(--earth-400)",
          500: "var(--earth-500)",
          600: "var(--earth-600)",
        },
      },
    },
  },
  plugins: [],
};